objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>ADMET</fullName>
                </value>
                <value>
                    <fullName>Aerospace</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Feed</fullName>
                </value>
                <value>
                    <fullName>API Synthesis/Scale-Up</fullName>
                </value>
                <value>
                    <fullName>Assay Development</fullName>
                </value>
                <value>
                    <fullName>Automotive &amp; Machinery</fullName>
                </value>
                <value>
                    <fullName>BEER BEV AND WINE</fullName>
                </value>
                <value>
                    <fullName>BioTech</fullName>
                </value>
                <value>
                    <fullName>Cancer</fullName>
                </value>
                <value>
                    <fullName>Cell Biology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>COMMERCIAL CONTRACT TESTING LABS</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>FEED &amp; PET FOOD</fullName>
                </value>
                <value>
                    <fullName>Forensic Science</fullName>
                </value>
                <value>
                    <fullName>Genomics/Genetics</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>GRAIN GENERAL &amp; TRADE UNPROCESSED (INCL FARMERS)</fullName>
                </value>
                <value>
                    <fullName>GRAIN PROCESSING (INCL STARCH PRODUCTION)</fullName>
                </value>
                <value>
                    <fullName>Hospitals &amp; Clinics</fullName>
                </value>
                <value>
                    <fullName>Immunology</fullName>
                </value>
                <value>
                    <fullName>Independent Testing</fullName>
                </value>
                <value>
                    <fullName>Lead Discovery</fullName>
                </value>
                <value>
                    <fullName>Lead Validation &amp; Optimization</fullName>
                </value>
                <value>
                    <fullName>LIQUID MILK</fullName>
                </value>
                <value>
                    <fullName>MEAT</fullName>
                </value>
                <value>
                    <fullName>Metals</fullName>
                </value>
                <value>
                    <fullName>Microbiology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academia</fullName>
                </value>
                <value>
                    <fullName>Aerospace</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Biofuels</fullName>
                </value>
                <value>
                    <fullName>Cellular Research</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical / Biomonitoring</fullName>
                </value>
                <value>
                    <fullName>Clinical Genetics and Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Consumer products and Product Safety</fullName>
                </value>
                <value>
                    <fullName>Consumer Products Supplier</fullName>
                </value>
                <value>
                    <fullName>Research and Drug Discovery</fullName>
                </value>
                <value>
                    <fullName>Electronics / Electroplating</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Foods &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Forensics</fullName>
                </value>
                <value>
                    <fullName>General Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Genomics</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Imaging</fullName>
                </value>
                <value>
                    <fullName>Life Science Research</fullName>
                </value>
                <value>
                    <fullName>Lubricants</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Mining / Metal</fullName>
                </value>
                <value>
                    <fullName>NGS</fullName>
                </value>
                <value>
                    <fullName>Nuclear</fullName>
                </value>
                <value>
                    <fullName>Nuclear Power and Radiation Safety</fullName>
                </value>
                <value>
                    <fullName>Nutraceuticals</fullName>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Rec_Date__c</fullName>
        <defaultValue>Today()+5</defaultValue>
        <inlineHelpText>Revenue Recognition Date. Typically set as 5 days from close date unless you provide a different date.</inlineHelpText>
        <label>Revenue Rec Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Dx_GBL_Opportunity_Record_Type</fullName>
        <active>true</active>
        <businessProcess>EMEA SDx Sales Process</businessProcess>
        <description>DX Sales process</description>
        <label>Dx Record Type</label>
    </recordTypes>
</CustomObject>

classes/test_revenue_rec_date_populatee.cls
@isTest
private class test_revenue_rec_date_populatee
{
  static testMethod void testinsert() {
    //create opportunity
    opportunity test_o = new opportunity();
    test_o.Name = 'Test';
    test_o.StageName = 'Abandoned';
    test_o.CloseDate = date.parse('3/10/2012');
    test_o.Revenue_rec_date__c = date.parse('3/1/2012');
    test_o.Market_Segment__c = 'Duplicate';
    test_o.Type = 'New Business';                                       
     insert test_o;                                    
    }
    static testmethod void testDealerPortal(){
       profile p = [select Id from Profile where Name = 'Dx Partner Community user'];
       Account a = new Account(Name='Test Account Name');
      insert a;
       Contact c = new contact(lastName='User',FirstName = 'Test',email = 'testuser3689@test.com', AccountId = a.Id);
       insert c;
        User u = new user(lastname = 'User' ,FirstName = 'test', username = 'testuser3689@test.com',profileId = p.Id
                         ,Email = 'testuser3689@test.com',Alias = 'tuser2',TimeZoneSidKey = 'America/new_york'
                         ,LocaleSidKey = 'en_US',EmailEncodingKey = 'UTF-8',LanguageLocaleKey='en_US',contactid = c.id);
        insert u;
        RecordType r = [select Id from RecordType Where DeveloperName = 'Dx_GBL_Opportunity_Record_Type'];
        Opportunity O = new Opportunity();
            o.name = 'test opp';
            O.StageName = 'Stage 1 - Qualification';
            o.RecordTypeId = r.id;
            o.CloseDate = Date.today().adddays(5);
        System.runAs(u){            
            insert o;
            o.StageName = 'Stage 4 - Objection Handling';
            update o;
            }
        Opportunity o1 = new Opportunity();
        o.name = 'test opp';
            o1.Name = 'test 2';
            o1.StageName = 'Stage 4 - Objection Handling';
            o1.RecordTypeId = r.id;
            o1.CloseDate = Date.today().adddays(5);
        insert o1;
       
            o1.StageName = 'Closed Won';
            update o1;

     
    }
 }