objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>PKI_SAP_Name_3__c</fullName>
        <description>SAP - KNA1/NAME3</description>
        <label>Institute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PKI_SAP_Name_4__c</fullName>
        <description>SAP - KNA1/NAME4</description>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Info__c</fullName>
        <description>Displays concatenated opportunity details on account</description>
        <formula>&apos;Open:&apos; + Text(No_Of_Open_Opportunities_INF__c) + &apos;/Closed:&apos; +  Text(No_Of_Closed_Won_Opportunities_INF__c)</formula>
        <label>Opportunity Info</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PKI_SAP_Account_Group__c</fullName>
        <defaultValue>&quot;SFDC&quot;</defaultValue>
        <label>SAP Account Group</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PKI_SAP_Customer_Number__c</fullName>
        <description>SAP - KNA1/KUNNR. Customer number for SoldToShipTo. IMPORTANT this is the external ID for the Customer Master integration used by Dell Boomi between SAP and SDFC. It is critical to the integrity of the data being passed from SAP</description>
        <externalId>true</externalId>
        <label>PKI SAP Customer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PKI_SAP_Customer_Base_Name__c</fullName>
        <description>SAP - KNA1/HNAME1. Standard name applied to all related accounts in the hierarchy</description>
        <label>PKI SAP Customer Base Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PKI_SAP_Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PKI SAP Marked for Deletion</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/searchAccountController.cls
public with sharing class searchAccountController {

 @AuraEnabled

public static List < account > fetchAccount(String searchKeyWord,String searchSAP,string searchCity, string searchStreet,string searchCountry) {
//Boolean PKIbase =false;
 String strSoqlQuery = 'Select  id, Name,PKI_SAP_Customer_Number__c,PKI_SAP_Customer_Base_Name__c,Opportunity_Info__c, ShippingCountry,ShippingCity, ShippingStreet,ShippingState,PKI_SAP_Name_3__c,PKI_SAP_Name_4__c from account where ';
String FixedFilter= '(PKI_SAP_Account_Group__c=\'0001\' OR PKI_SAP_Account_Group__c=\'SFDC\') AND (PKI_SAP_Marked_For_Deletion__c=false)' ;
    
    list <account> lstOfAccount= new list <account> ();
    
if(!string.isblank(searchKeyWord)){
string nam=searchKeyWord.trim();
 String NameKey ='%'+nam+'%';
FixedFilter+='AND Name LIKE \'%' + NameKey +  '%\' ' ;
}

if(!string.isblank(searchSAP)){
//string sap=searchSAP.trim();
 String sapNo =searchSAP;
FixedFilter+='AND PKI_SAP_Customer_Number__c=:sapNo ' ;
}

if(!string.isblank(searchStreet)){
//string site=searchStreet.trim();
 String siteS =searchStreet;
FixedFilter+='AND ShippingStreet LIKE \'%' + siteS +  '%\' ' ;
}

if(!string.isblank(searchCity)){
string street=searchCity.trim();
 String streetc ='%'+street+'%';
FixedFilter+='AND ShippingCity LIKE \'%' + streetc +  '%\' ' ;
}
    if(!string.isblank(searchCountry)){
string streetco=searchCountry.trim();
 String streetS ='%'+streetco+'%';
FixedFilter+='AND ShippingCountry=: streetco  ' ;
}


strSoqlQuery+=FixedFilter+' ORDER BY Opportunity_Info__c DESC LIMIT 200';
    system.debug('---strSoqlQuery '+strSoqlQuery);
    try{lstOfAccount= Database.query(strSoqlQuery);}catch (QueryException e){ system.debug('Query Exception:'+e.getMessage());return null;}

system.debug('---lstOfAccount '+lstOfAccount);

  return lstOfAccount;

}

}