objects/Case_Event__e.object
<CustomObject>
    <description>A Platform Event indicating that a Case Integration Event has occurred</description>
    <label>Case Event</label>
    <pluralLabel>Case Events</pluralLabel>
    <fields>
        <fullName>CaseId__c</fullName>
        <label>CaseId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SMAX_PS_CaseEvent_UT.cls
@isTest(seeAlldata=false)
public class SMAX_PS_CaseEvent_UT {

    // Not a valid "test", but need code coverage.. 
    // We found that if seeAllData is true, Platform Event triggers don't fire.
    // BUT, can't create a Case without seeAllData=true
    static testMethod void caseEventTest() {
        // Case event
        Test.startTest();
        Case_Event__e cEvent = new Case_Event__e (
                                    CaseId__c = 'Test Case Id');
        Database.SaveResult sr = EventBus.publish(cEvent);
        Test.stopTest();
   }
}