objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Product_Line__c</fullName>
        <inlineHelpText>This field maps over from the Lead Page</inlineHelpText>
        <label>Product Line</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>ANP</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>ARS</fullName>
                </value>
                <value>
                    <fullName>ATT</fullName>
                </value>
                <value>
                    <fullName>AVC</fullName>
                </value>
                <value>
                    <fullName>AVS</fullName>
                </value>
                <value>
                    <fullName>AWS</fullName>
                </value>
                <value>
                    <fullName>BIO</fullName>
                </value>
                <value>
                    <fullName>BTX</fullName>
                </value>
                <value>
                    <fullName>CLH</fullName>
                </value>
                <value>
                    <fullName>CLR</fullName>
                </value>
                <value>
                    <fullName>CRD</fullName>
                </value>
                <value>
                    <fullName>CSA</fullName>
                </value>
                <value>
                    <fullName>DAB</fullName>
                </value>
                <value>
                    <fullName>DAO</fullName>
                </value>
                <value>
                    <fullName>DCS</fullName>
                </value>
                <value>
                    <fullName>DEL</fullName>
                </value>
                <value>
                    <fullName>DIA</fullName>
                </value>
                <value>
                    <fullName>DIS</fullName>
                </value>
                <value>
                    <fullName>DL</fullName>
                </value>
                <value>
                    <fullName>DLS</fullName>
                </value>
                <value>
                    <fullName>DNA</fullName>
                </value>
                <value>
                    <fullName>DSK</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>ELM</fullName>
                </value>
                <value>
                    <fullName>ENT</fullName>
                </value>
                <value>
                    <fullName>ESS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Area_of_Interest__c</fullName>
        <description>ANNUITAS PDG Program</description>
        <label>Solution Area of Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Applied Genomics</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Digital Lab</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Food Quality</fullName>
                </value>
                <value>
                    <fullName>Food Safety</fullName>
                </value>
                <value>
                    <fullName>Forensics and Security</fullName>
                </value>
                <value>
                    <fullName>Geochemistry, Mining and Metals</fullName>
                </value>
                <value>
                    <fullName>Disease Research</fullName>
                    <label>Life Science Research</label>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
                <value>
                    <fullName>Maternal Fetal Health</fullName>
                </value>
                <value>
                    <fullName>Newborn Screening</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Studies</fullName>
                    <label>Pre-Clinical Drug Development</label>
                </value>
                <value>
                    <fullName>Drug Discovery</fullName>
                    <label>Pre-Clinical Drug Discovery</label>
                </value>
                <value>
                    <fullName>QA/QC Drug Manufacturing Process</fullName>
                </value>
                <value>
                    <fullName>Soil/Solids</fullName>
                </value>
                <value>
                    <fullName>Strategic Services</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Type_INF__c</fullName>
        <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
        <inlineHelpText>Price List requires Acct Type</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                    <default>true</default>
                    <label>Commercial</label>
                </value>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Rec_Date__c</fullName>
        <defaultValue>Today()+5</defaultValue>
        <inlineHelpText>Revenue Recognition Date. Typically set as 5 days from close date unless you provide a different date.</inlineHelpText>
        <label>Revenue Rec Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Required_INF__c</fullName>
        <label>Renewal Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Area_of_Interest__c</fullName>
        <description>ANNUITAS PDG Program</description>
        <label>Solution Area of Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Applied Genomics</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Digital Lab</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Food Quality</fullName>
                </value>
                <value>
                    <fullName>Food Safety</fullName>
                </value>
                <value>
                    <fullName>Forensics and Security</fullName>
                </value>
                <value>
                    <fullName>Geochemistry, Mining and Metals</fullName>
                </value>
                <value>
                    <fullName>Disease Research</fullName>
                    <label>Life Science Research</label>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
                <value>
                    <fullName>Maternal Fetal Health</fullName>
                </value>
                <value>
                    <fullName>Newborn Screening</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Studies</fullName>
                    <label>Pre-Clinical Drug Development</label>
                </value>
                <value>
                    <fullName>Drug Discovery</fullName>
                    <label>Pre-Clinical Drug Discovery</label>
                </value>
                <value>
                    <fullName>QA/QC Drug Manufacturing Process</fullName>
                </value>
                <value>
                    <fullName>Soil/Solids</fullName>
                </value>
                <value>
                    <fullName>Strategic Services</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Processing_Status_INF__c</fullName>
        <label>Order Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Revenue Review Required</fullName>
                </value>
                <value>
                    <fullName>AR Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Informatics</fullName>
        <active>true</active>
        <businessProcess>Informatics</businessProcess>
        <description>Informatics Sales Process (modified SPI)</description>
        <label>Informatics</label>
    </recordTypes>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Type_INF__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Perpetual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date_INF__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>PricebookEntry.Product2.product_line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Family )</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <formula>IF( PricebookEntry.Product2.IsActive=TRUE, &quot;ACTIVE&quot;, &quot;INACTIVE&quot;)</formula>
        <label>Product Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_INF__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>product_line__c</fullName>
        <description>Product Line code from SAP</description>
        <label>Product Line</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Type_INF__c</fullName>
        <label>License Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type_INF__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/TestCreateRenewalOppClosedWon.cls
@isTest(seeAllData=true)
private class TestCreateRenewalOppClosedWon {
static testMethod void CreateRenewalOnlosedWonOpportunity(){
Set<Id> SetOfOppIds = new Set<Id>();
    
    /* Added by Gireesh AccountId='0013000001DIhdl' */
    List<Opportunity> newOpps = new List<Opportunity>();
     List<Opportunity> listOfOpp = new List<Opportunity>();
     
     Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.shippingStreet = 'Street1';
            ac.shippingCity = 'City1';
            ac.shippingState = 'State';
            ac.shippingCountry ='US';
            ac.shippingPostalCode = '12345';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
    
        for (Integer i = 0; i < 10; i++)
         {  
             
            // RecordType optyrecordtype = [select id from recordType where Name='informatics' limit 1];
           newOpps.add(new Opportunity(Name='opp'+i,AccountId=ac.Id,Probability=99,Renewal_Required_INF__c='Yes',RecordTypeId='01230000001aIi6',Account_Type_INF__c='Academic',Primary_Contact__c=co.Id,StageName='Stage 7 - Submit Order',CloseDate=Date.today(),Revenue_Rec_Date__c = Date.today(),Solution_Area_of_Interest__c='Energy'));
         }
        insert newOpps;
        
        
//get standard pricebook
Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];


Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
insert pbk1;

Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 1');
insert prd1;

Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 2');
insert prd2;

Product2 prd3 = new Product2 (Name='test product',ProductCode='CPH569',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 3');
insert prd3;



PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
        UseStandardPrice=false,UnitPrice=50);
insert pbe2;

// Create a task for each one
List<OpportunityLineItem> newLineItems = new List<OpportunityLineItem>();
List<Opportunity> OppsUpdate = new List<Opportunity>();
  

for(Opportunity opp : newOpps){
newLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe2.id));
//newLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe2.id));
SetOfOppIds.add(opp.id);
}
insert newLineItems;

 /*for(Opportunity op :[Select Id,
                          (Select Type_INF__c, PricebookEntry.Product2.License_Type_INF__c,Start_Date_INF__c, Product_Status__c,
                           Product_Line__c,Quantity, Product_Family__c,OpportunityId, Id, End_Date_INF__c,PricebookEntryId,
                           UnitPrice,PricebookEntry.Product2.Product_Type_INF__c From OpportunityLineItems
                           WHERE (PricebookEntry.Product2.License_Type_INF__c ='Services' OR PricebookEntry.Product2.Product_Type_INF__c ='Services'))                                    
                        From Opportunity o where Id IN:SetOfOppIds]){
    
    if(op.OpportunityLineItems.size()>0)
    {
       for(OpportunityLineItem opp : op.OpportunityLineItems)
           {
             op.Order_Processing_Status_INF__c = 'Revenue Review Required';
             listOfOpp.add(op);           
           } 
             if(listOfOpp.size()>0)
                  update listOfOpp;    
      } 
}*/

    
}

    
}