objects/Demo_Log__c.object
<CustomObject>
    <label>Demo Log</label>
    <nameField>
        <displayFormat>INF-RML-{000000000}</displayFormat>
        <label>Demo Request No#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Product_INF__c</fullName>
        <label>Primary Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Attivio</fullName>
                </value>
                <value>
                    <fullName>CAFÉ  - Medical Review</fullName>
                </value>
                <value>
                    <fullName>CAFÉ - RBM</fullName>
                </value>
                <value>
                    <fullName>CAFÉ - RWE</fullName>
                </value>
                <value>
                    <fullName>ChemDraw</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Elements</fullName>
                </value>
                <value>
                    <fullName>E-Notebook Biology</fullName>
                </value>
                <value>
                    <fullName>E-Notebook Chemistry</fullName>
                </value>
                <value>
                    <fullName>E-Notebook Formulations</fullName>
                </value>
                <value>
                    <fullName>iLab</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Inventory Ent</fullName>
                </value>
                <value>
                    <fullName>LimsLink</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>Signals Clinical</fullName>
                </value>
                <value>
                    <fullName>Signals Lead Discovery</fullName>
                </value>
                <value>
                    <fullName>Signals Medical Review</fullName>
                </value>
                <value>
                    <fullName>Signals Notebook</fullName>
                </value>
                <value>
                    <fullName>Signals Notebook - Biology</fullName>
                </value>
                <value>
                    <fullName>Signals Notebook - Chemistry</fullName>
                </value>
                <value>
                    <fullName>Signals Notebook for ChemDraw</fullName>
                </value>
                <value>
                    <fullName>Signals Screening</fullName>
                </value>
                <value>
                    <fullName>Signals Translational</fullName>
                </value>
                <value>
                    <fullName>Spotfire Biology</fullName>
                </value>
                <value>
                    <fullName>Spotfire Chemistry</fullName>
                </value>
                <value>
                    <fullName>Spotfire Clinical</fullName>
                </value>
                <value>
                    <fullName>Spotfire for Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Spotfire High Content Profiler</fullName>
                </value>
                <value>
                    <fullName>Spotfire OmicsOffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DemoLogTestClass.cls
@isTest
public class DemoLogTestClass {
	@isTest
    public static void TestDemoLogExpiration(){
        PageReference p = Page.DemoLogExpiration;
        test.setCurrentPage(p);
        
        Demo_Log__c d = new Demo_Log__c();
        d.RecordTypeId = Schema.getGlobalDescribe().get('Demo_log__c').getDescribe().getRecordTypeInfosbyName().get('System Request').getRecordTypeid();
		d.Primary_Product_INF__c = 'Registration';
        d.Expiration_Date__c = Date.today();
        insert d;
        
       ApexPages.currentPage().getParameters().put('Id',d.id);
       ApexPages.currentPage().getParameters().put('Days','30 Days');
       ApexPages.currentPage().getParameters().put('typ','Parked'); 
       ApexPages.currentPage().getParameters().put('Status','OFF');  
        
        DemoLogExpirationController dc = new DemoLogExpirationController();
        dc.submit();
        
    }
}