objects/Demo_Log__c.object
<CustomObject>
    <label>Demo Log</label>
    <nameField>
        <displayFormat>INF-RML-{000000000}</displayFormat>
        <label>Demo Request No#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Type2__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Parked</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Template</fullName>
                </value>
                <value>
                    <fullName>Cloud Parked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default_Status__c</fullName>
        <label>Default Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Days_Active__c</fullName>
        <label>System Days Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 days</fullName>
                </value>
                <value>
                    <fullName>60 days</fullName>
                </value>
                <value>
                    <fullName>90 days</fullName>
                </value>
                <value>
                    <fullName>120 days</fullName>
                </value>
                <value>
                    <fullName>150 days</fullName>
                </value>
                <value>
                    <fullName>180 days</fullName>
                </value>
                <value>
                    <fullName>Retire</fullName>
                </value>
                <value>
                    <fullName>15 days</fullName>
                    <isActive>false</isActive>
                    <label>15 days</label>
                </value>
                <value>
                    <fullName>360 days</fullName>
                    <isActive>false</isActive>
                    <label>360 days</label>
                </value>
                <value>
                    <fullName>7 days</fullName>
                    <isActive>false</isActive>
                    <label>7 days</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DemoLogExpirationController.cls
public class DemoLogExpirationController {
    public String Did {get;set;}
    public String DemologName {get;set;}
    public String ActDays {get;set;}
    Public String Type {get;set;}
    Public String Status {get;set;}  
    Public Demo_Log__c d;
    public DemoLogExpirationController(){

        Did = ApexPages.currentPage().getparameters().get('Id');
        d = [Select id,Name,System_Days_Active__c,Default_Status__c,Type2__c From Demo_Log__c Where Id = :Did];
        DemologName = d.Name;
        ActDays = ApexPages.currentPage().getparameters().get('Days');
        Type = (ApexPages.currentPage().getparameters().get('typ') != 'null')?(ApexPages.currentPage().getparameters().get('typ')):d.Type2__c;
        Status = (ApexPages.currentPage().getparameters().get('Status') != 'null')?(ApexPages.currentPage().getparameters().get('Status')):d.Default_Status__c;

     }
    public PageReference submit(){
        d.System_Days_Active__c = ActDays;
        d.Type2__c = Type;
        d.Default_Status__c = Status;
        update d;
        pageReference p = new PageReference('/' + d.id);
        p.setRedirect(true);
        return p;
    }
}