objects/Interaction_Assignment__c.object
<CustomObject>
    <label>Interaction Assignment</label>
    <nameField>
        <label>SFDC Integration  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interaction Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SAI__c</fullName>
        <label>SAI</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interaction_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Region__c</fullName>
        <label>Country/Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Interaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Interaction</label>
        <referenceTo>SFDC_Interaction__c</referenceTo>
        <relationshipLabel>Interaction Assignments</relationshipLabel>
        <relationshipName>Interaction_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SFDC_Interaction__c.object
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>SFDC-{0000}</displayFormat>
        <label>SFDC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Assigned</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SFDC_Interaction_user</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Area_of_Interest__c</fullName>
        <label>Solution Area of Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Applied Genomics</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Digital Lab</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Forensics and Security</fullName>
                </value>
                <value>
                    <fullName>Geochemistry, Mining and Metals</fullName>
                </value>
                <value>
                    <fullName>Life Science Research</fullName>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
                <value>
                    <fullName>Maternal Fetal Health</fullName>
                </value>
                <value>
                    <fullName>Newborn Screening</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Drug Development</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Drug Discovery</fullName>
                </value>
                <value>
                    <fullName>QA/QC Drug Manufacturing Process</fullName>
                </value>
                <value>
                    <fullName>Soil/Solids</fullName>
                </value>
                <value>
                    <fullName>Strategic Services</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Food Quality</fullName>
                    <isActive>false</isActive>
                    <label>Food Quality</label>
                </value>
                <value>
                    <fullName>Food Safety</fullName>
                    <isActive>false</isActive>
                    <label>Food Safety</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/InteractionAssignment.cls
public class InteractionAssignment{

public static void InteractionAssignmenthelper(list<SFDC_Interaction__c> SIList){

string region,pl,sai;

for(SFDC_Interaction__c si:SIList){
region=si.Global_Region__c;
pl=si.Product_Line__c;
sai=si.Solution_Area_of_Interest__c;

}
string strQuery='select id,Product_Line__c,Country_Region__c,SAI__c,User__c,User__r.ID,OwnerId from Interaction_Assignment__c where ';
    system.debug('---inputs '+region+pl+sai);
if(!string.isblank(region)){
strQuery=strQuery+ ' Country_Region__c=:region '; 
}
if(!string.isblank(pl)){
strQuery=strQuery+'AND Product_Line__c=:pl ';
}
if(!string.isblank(sai)){
strQuery=strQuery+'AND SAI__c=:sai ';
}
strQuery=strQuery+' limit 10';
    system.debug('---strQuery '+strQuery);
Interaction_Assignment__c IA=Database.query(strQuery);
system.debug('---IA '+IA); 
if(IA!=null){
for(SFDC_Interaction__c SI:SIList){
SI.OwnerId=IA.OwnerId;
}
}
}
}