objects/Lead.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Is_PDG_Routing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To mark the record that has gone through PDG routing.</description>
        <label>Is PDG Routing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PDG_Start_Time__c</fullName>
        <description>Gets stamped with the start time for the SLA</description>
        <label>PDG Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Owner_LDR_QL__c</fullName>
        <description>ANNUITAS PDG Program</description>
        <label>Lead Owner - LDR QL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>First_Owner_Changed__c</fullName>
        <description>Gets stamped with yes or no</description>
        <label>First Owner Changed</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_Routing_Tracking__c</fullName>
        <description>Tracks lead process through the route</description>
        <label>PDG Routing Tracking</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alert_First_Owner_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, the records Owner will be sent an email</description>
        <label>Alert First Owner Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispensation_SAI_Current_Status__c</fullName>
        <description>Formula evaluates to true if all conditions are met. For Lead SLA Process</description>
        <formula>OR
(
IF(TEXT(Status_Strategic_Services__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Strategic_Services__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Disease_Research__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Disease_Research__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Drug_Discovery__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Drug_Discovery__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Pre_Clinical_Studies__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Pre_Clinical_Studies__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Clinical_Studies__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Clinical_Studies__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_QA_QC_Drug_Manufacturing_Process__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_QA_QC_Drug_Manufacturing_Process__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Digital_Lab__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Digital_Lab__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Food_Quality__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Food_Quality__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Food_Safety__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Food_Safety__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Material__c) = &apos;Open&apos;, True, False),
IF(TEXT(Status_Material__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Chemicals__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Chemicals__c) = &apos;Re-Qualified&apos;, True, False), 
IF(TEXT(Status_Energy__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Energy__c) = &apos;Re-Qualified&apos;, True, False), 
IF(TEXT(Status_Geochemistry_Mining_and_Metals__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Geochemistry_Mining_and_Metals__c) = &apos;Re-Qualified&apos;, True, False), 
IF(TEXT(Status_Forensics_and_Security__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Forensics_and_Security__c) = &apos;Re-Qualified&apos;, True, False), 
IF(TEXT(Status_Water__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Water__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Air__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Air__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Soil_Solids__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Soil_Solids__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Maternal_Fetal_Health__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Maternal_Fetal_Health__c) = &apos;Re-Qualified&apos;, True, False),
IF(TEXT(Status_Newborn_Screening__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Newborn_Screening__c) = &apos;Re-Qualified&apos;, True, False), 
IF(TEXT(Status_Applied_Genomics__c) = &apos;Open&apos;, True, False), 
IF(TEXT(Status_Applied_Genomics__c) = &apos;Re-Qualified&apos;, True, False) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dispensation SAI Current Status</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/PDG_Public_Group_Names__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the names of the public groups for PDG Lead routing</description>
    <label>PDG Public Group Names</label>
    <fields>
        <fullName>PDG_HOT_APAC__c</fullName>
        <description>PDG HOT APAC public group</description>
        <label>PDG HOT APAC</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_HOT_EMEA__c</fullName>
        <description>PDG HOT EMEA public group</description>
        <label>PDG HOT EMEA</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_GROW_LDRs__c</fullName>
        <description>PDG GROW LDRs public group</description>
        <label>PDG GROW LDRs</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_LDR_To_Dx__c</fullName>
        <description>PDG LDR To Dx public group</description>
        <label>PDG LDR To Dx</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_WARM_APAC__c</fullName>
        <description>PDG WARM APAC public group</description>
        <label>PDG WARM APAC</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_WARM_EMEA__c</fullName>
        <description>PDG WARM EMEA public group</description>
        <label>PDG WARM EMEA</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_HOT_Americas__c</fullName>
        <description>PDG HOT Americas public group</description>
        <label>PDG HOT Americas</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDG_WARM_Americas__c</fullName>
        <description>PDG WARM Americas public group name</description>
        <label>PDG WARM Americas</label>
        <length>225</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/PDG_Assign_Lead.cls
public class PDG_Assign_Lead{
    public static String chars = '123456789';
    public static PDG_Public_Group_Names__c pubGrNames = PDG_Public_Group_Names__c.getInstance();
    public static List <Lead> storeRoutedLead = new List <Lead>();
    
   /* public static string createRandStr(){
        String randStr = '';
        while (randStr.length() < 2) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr;
    } */
    public static void WarmRecords(map <String,List<Lead>> Records) {
        system.debug(LoggingLevel.Info,'%%getCpuTime()***'+Limits.getCpuTime());
        
        List <GroupMember> WarmAmericas = [SELECT Id, userorgroupid 
                                           FROM GroupMember WHERE group.Name = :pubGrNames.PDG_WARM_Americas__c];
        List <GroupMember> WarmEMEA = [SELECT Id, userorgroupid 
                                       FROM GroupMember WHERE group.Name = :pubGrNames.PDG_WARM_EMEA__c];
        List <GroupMember> WarmAPAC = [SELECT Id, userorgroupid 
                                       FROM GroupMember WHERE group.Name = :pubGrNames.PDG_WARM_APAC__c];
        
        
        
        Integer AmericasCount = WarmAmericas.size();
        Integer EMEACount = WarmEMEA.size();
        Integer APACCount = WarmAPAC.size();
        
        system.debug('[Class] <PDG_Assign_Lead> Map : ' + Records);    
        
        for(String s : Records.keySet()){
            for(Lead a :Records.get(s)){
                String randStr = '';
                while (randStr.length() < 2) {
                    Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
                    randStr += chars.substring(idx, idx+1);
                }
                system.debug('[Class] <PDG_Assign_Lead> randStr : ' + randStr);    
                
                if(AmericasCount > 0 && s.equals('Americas')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), AmericasCount);
                    system.debug('[Class] <PDG_Assign_Lead> Warm Americas membersize : ' + AmericasCount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = WarmAmericas[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'Americas';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + WarmAmericas[roundRobinIdx].UserOrGroupId);    
                }
                if(EMEACount > 0 && s.equals('EMEA')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), EMEACount);
                    system.debug('[Class] <PDG_Assign_Lead> Warm EMEA membersize : ' + EMEACount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = WarmEMEA[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'EMEA';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + WarmEMEA[roundRobinIdx].UserOrGroupId);                     
                }
                if(APACCount > 0 && s.equals('APAC')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), APACCount);
                    system.debug('[Class] <PDG_Assign_Lead> Warm APAC membersize : ' + APACCount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = WarmAPAC[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'APAC';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + WarmAPAC[roundRobinIdx].UserOrGroupId);                  
                }
                
            }
        }
        StampLeadOwner();
    }
    
    public static void HotRecords(map <String,List<Lead>> Records) {
        system.debug(LoggingLevel.Info,'%%getCpuTime()***'+Limits.getCpuTime());
        List <GroupMember> HotAmericas = [SELECT Id, userorgroupid 
                                          FROM GroupMember WHERE group.Name = :pubGrNames.PDG_HOT_Americas__c];
        List <GroupMember> HotEMEA = [SELECT Id, userorgroupid 
                                      FROM GroupMember WHERE group.Name = :pubGrNames.PDG_HOT_EMEA__c];
        List <GroupMember> HotAPAC = [SELECT Id, userorgroupid 
                                      FROM GroupMember WHERE group.Name = :pubGrNames.PDG_HOT_APAC__c];
        
        
        Integer AmericasCount = HotAmericas.size();
        Integer EMEACount = HotEMEA.size();
        Integer APACCount = HotAPAC.size();
        
        system.debug('[Class] <PDG_Assign_Lead> Map : ' + Records);    
        
        for(String s : Records.keySet()){
            for(Lead a :Records.get(s)){
                String randStr = '';
                while (randStr.length() < 2) {
                    Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
                    randStr += chars.substring(idx, idx+1);
                }
                
                system.debug('[Class] <PDG_Assign_Lead> randStr : ' + randStr);    
                if(AmericasCount > 0 && s.equals('Americas')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), AmericasCount);
                    system.debug('[Class] <PDG_Assign_Lead> Hot Americas membersize : ' + AmericasCount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = HotAmericas[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'Americas';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + HotAmericas[roundRobinIdx].UserOrGroupId);    
                }
                
                if(EMEACount > 0 && s.equals('EMEA')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), EMEACount);
                    system.debug('[Class] <PDG_Assign_Lead> Hot EMEA membersize : ' + EMEACount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = HotEMEA[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'EMEA';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + HotEMEA[roundRobinIdx].UserOrGroupId);                     
                }
                
                if(APACCount > 0 && s.equals('APAC')){
                    Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), APACCount);
                    system.debug('[Class] <PDG_Assign_Lead> Hot APAC membersize : ' + APACCount); 
                    system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                    a.OwnerId = HotAPAC[roundRobinIdx].UserOrGroupId;
                    a.Alert_First_Owner_Email__c = true;
                    a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'APAC';
                    a.Is_PDG_Routing__c = true;//miss routing fix
                    storeRoutedLead.add(a);
                    system.debug('[Class] <PDG_Assign_Lead> UserId : ' + HotAPAC[roundRobinIdx].UserOrGroupId);                     
                }
            }
        }
        StampLeadOwner();
        system.debug(LoggingLevel.Info,'%%getCpuTime()***'+Limits.getCpuTime());
    }
    public static void LDR_To_Dx(List <Lead> Records) {
        
        List <GroupMember> DX_LDRs = [SELECT Id, userorgroupid 
                                      FROM GroupMember WHERE group.Name = :pubGrNames.PDG_LDR_To_Dx__c]; 
        
        Integer DxLDRCount = DX_LDRs.size();
        
        for(Lead a : Records){
            String randStr = '';
            while (randStr.length() < 2) {
                Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
                randStr += chars.substring(idx, idx+1);
            }
            
            system.debug('[Class] <PDG_Assign_Lead> randStr : ' + randStr);    
            
            if(DX_LDRs.size() > 0){
                Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), DxLDRCount);
                system.debug('[Class] <PDG_Assign_Lead> Dx membersize : ' + DxLDRCount); 
                system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                a.OwnerId = DX_LDRs[roundRobinIdx].UserOrGroupId;
                a.Alert_First_Owner_Email__c = true;
                a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'DX_LDR';
                a.Is_PDG_Routing__c = true;//miss routing fix
                storeRoutedLead.add(a);
                system.debug('[Class] <PDG_Assign_Lead> UserId : ' + DX_LDRs[roundRobinIdx].UserOrGroupId);    
            }
        }
        StampLeadOwner();
    }
    
    
    public static void GROW_LDR(List <Lead> Records) {
        
        List <GroupMember> GROW_LDRs = [SELECT Id, userorgroupid 
                                        FROM GroupMember WHERE group.Name =:pubGrNames.PDG_GROW_LDRs__c]; 
        
        Integer GROWLDRCount = GROW_LDRs.size();
        
        for(Lead a : Records){
            String randStr = '';
        while (randStr.length() < 2) {
                    Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
                    randStr += chars.substring(idx, idx+1);
                }
            system.debug('[Class] <PDG_Assign_Lead> randStr : ' + randStr);    
            if(GROW_LDRs.size() > 0){
                Integer roundRobinIdx = Math.mod(Integer.valueOf(randStr), GROWLDRCount);
                system.debug('[Class] <PDG_Assign_Lead> GROW membersize : ' + GROWLDRCount); 
                system.debug('[Class] <PDG_Assign_Lead> Index : ' + roundRobinIdx);    
                a.OwnerId = GROW_LDRs[roundRobinIdx].UserOrGroupId;
                a.First_Owner_Changed__c = 'Yes';
                a.PDG_Routing_Tracking__c = a.PDG_Routing_Tracking__c + 'GROW';
                a.Is_PDG_Routing__c = true;//miss routing fix
                if(a.PDG_Start_Time__c == null && a.Dispensation_SAI_Current_Status__c){
                    a.PDG_Start_Time__c = DateTime.now();
                    system.debug('[Class] <PDG_Routing> Time updated : ' + a.PDG_Start_Time__c);
                }                
                
                storeRoutedLead.add(a);
                system.debug('[Class] <PDG_Assign_Lead> UserId : ' + GROW_LDRs[roundRobinIdx].UserOrGroupId);    
            }
        }
        StampLeadOwner();
    } 
    
    
    public static void StampLeadOwner(){
        Map <Id,Id> manager_Id = new Map <Id,Id>();
        system.debug('[Class] <PDG_Assign_Lead> StampLeadOwner : ' + storeRoutedLead.size());    
        List <ID> storeIds = new List <ID>();
        
        if(storeRoutedLead.size() > 0){
            for(Lead ownerId : storeRoutedLead){
                if(!storeIds.contains(ownerId.ownerId)){
                    storeIds.add(ownerid.ownerId);
                    system.debug('[Class] <PDG_Assign_Lead> storeIds : ' + ownerId);
                }
            }
            
        }
        
        if(storeIds.size() > 0){
            system.debug('[Class] <PDG_Assign_Lead> storeIds : ' + storeIds.size());    
            Map <Id, User> us = new Map <Id, User>([Select id, Name From User where id=:storeIds]);
            system.debug('[Class] <PDG_Assign_Lead> User : ' + us);    
            
            for(Lead a : storeRoutedLead){          
                if(string.isEmpty(a.Lead_Owner_LDR_QL__c)){
                    system.debug('[Class] <PDG_Assign_Lead> Lead_Owner_LDR_QL__c : ' + us.get(a.ownerId).Name);    
                    a.Lead_Owner_LDR_QL__c = us.get(a.ownerId).Name;
                }
            }
        }
        system.debug(LoggingLevel.Info,'%%getCpuTime()***'+Limits.getCpuTime());
        
    }
    
    
}