objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Quote_Name__c</fullName>
        <label>Quote Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type_INF__c</fullName>
        <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
        <inlineHelpText>Price List requires Acct Type</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                    <default>true</default>
                    <label>Commercial</label>
                </value>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Required_INF__c</fullName>
        <label>Renewal Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Market_INF__c</fullName>
        <label>Strategic Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Life Sciences Research</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Clinical &amp; Translational</fullName>
                </value>
                <value>
                    <fullName>Related Markets</fullName>
                </value>
                <value>
                    <fullName>Production Support</fullName>
                </value>
                <value>
                    <fullName>Academic &amp; Government</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Area_of_Interest__c</fullName>
        <description>ANNUITAS PDG Program</description>
        <label>Solution Area of Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Applied Genomics</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Digital Lab</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Food Quality</fullName>
                </value>
                <value>
                    <fullName>Food Safety</fullName>
                </value>
                <value>
                    <fullName>Forensics and Security</fullName>
                </value>
                <value>
                    <fullName>Geochemistry, Mining and Metals</fullName>
                </value>
                <value>
                    <fullName>Disease Research</fullName>
                    <label>Life Science Research</label>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
                <value>
                    <fullName>Maternal Fetal Health</fullName>
                </value>
                <value>
                    <fullName>Newborn Screening</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Studies</fullName>
                    <label>Pre-Clinical Drug Development</label>
                </value>
                <value>
                    <fullName>Drug Discovery</fullName>
                    <label>Pre-Clinical Drug Discovery</label>
                </value>
                <value>
                    <fullName>QA/QC Drug Manufacturing Process</fullName>
                </value>
                <value>
                    <fullName>Soil/Solids</fullName>
                </value>
                <value>
                    <fullName>Strategic Services</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Name__c</fullName>
        <label>Quote Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/quote_trgTest.cls
@isTest(seeAllData=true)
public class quote_trgTest {
    static testMethod void Test_Method1(){
        Account a = new Account(Name='Testing3456',shippingCountry='US',Industry ='Biotech',
                                BillingStreet='Street1',BillingCity='City1',BillingState='State',BillingCountry='US',BillingPostalCode='12345');
        insert a;
        Opportunity op = new Opportunity(Name='opp1',AccountId=a.Id,RecordTypeId='01230000001aIi6',
                                              Renewal_Required_INF__c='Yes',Account_Type_INF__c='Academic',
                                              StageName='Stage 1 - Create/Plan',CloseDate=Date.today(),
                                              Strategic_Market_INF__c='Clinical',Type='New Account',
                                              ForecastCategoryName='Pipeline',CurrencyIsoCode = 'USD',
                                        	  Solution_Area_of_Interest__c='Energy');        
        insert op;
        SBQQ__Quote__c q = new SBQQ__Quote__c(Quote_Name__c='Q1213',SBQQ__Primary__c=true,SBQQ__StartDate__c=Date.today(),
                                              SBQQ__Account__c=a.Id,SBQQ__Opportunity2__c=op.Id,ApprovalStatus__c='Pending');
        insert q;
    }
}