objects/SBQQ__Quote__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Locked</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
</CustomObject>

classes/LockRecord.cls
public without sharing class LockRecord {

    @InvocableMethod
    public static void lockRecords(List<Id> QuoteList)
    {
            List<SBQQ__Quote__c> QuoteId = new List<SBQQ__Quote__c>();
            List<SBQQ__QuoteLine__c> QuoteLines = new List<SBQQ__QuoteLine__c>();
            
            QuoteId = [Select id,Approval_Locked__c from SBQQ__Quote__c where id=:QuoteList];
            if(QuoteId.size()>0)
            {
                QuoteLines = [select id from SBQQ__QuoteLine__c where SBQQ__Quote__c=:QuoteId];
                Approval.LockResult[] lrOptyList = Approval.lock(QuoteId, false);
            }
            if(QuoteLines.size()>0)
            {
                Approval.LockResult[] lrList = Approval.lock(QuoteLines, false);
            }
            
    }
}